
export enum MessageType {
    INIT_API = 'NP_CHECKIN_INIT_API',
    PRINT_LABEL = 'NP_CHECKIN_PRINT_LABEL',
    ACTION_SUCCESS = 'NP_CHECKIN_ACTION_SUCCESS',
    ACTION_ERROR = 'NP_CHECKIN_ACTION_ERROR',
    GET_APP_SETTING = 'NP_CHECKIN_GET_APP_SETTING',
    SET_APP_SETTING = 'NP_CHECKIN_SET_APP_SETTING',
    SHOW_SETTINGS = 'NP_CHECKIN_SHOW_SETTINGS'
}
